---
- name: Configure High Availability SonarQube Nodes
  hosts: all
  become: yes
  vars:
    # Passed dynamically from Jenkins/Terraform later
    db_host: "REPLACE_WITH_DB_ENDPOINT"
  tasks:
    - name: 1. Set Kernel Optimization Parameters
      sysctl:
        name: vm.max_map_count
        value: '524288'
        state: present
        reload: yes

    - name: 2. Install Docker Prerequisites
      apt:
        name: [apt-transport-https, ca-certificates, curl, gnupg, lsb-release]
        state: present
        update_cache: yes

    - name: 3. Setup Docker Keyring and Repo
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -y -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.data/docker.list > /dev/null

    - name: 4. Install Docker Engine
      apt:
        name: [docker-ce, docker-ce-cli, containerd.io, docker-compose-plugin]
        state: present
        update_cache: yes

    - name: 5. Create Stack Directory
      file:
        path: /opt/sonar-ha-stack
        state: directory
        mode: '0755'

    - name: 6. Template out Docker Compose Configuration
      copy:
        dest: /opt/sonar-ha-stack/docker-compose.yml
        content: |
          version: '3.8'
          services:
            sonarqube:
              image: sonarqube:10.4.1-community
              container_name: sonarqube_node
              ports:
                - "9000:9000"
              environment:
                - SONAR_JDBC_USERNAME=sonar
                - SONAR_JDBC_PASSWORD=SonarSecure2026!
                - SONAR_JDBC_URL=jdbc:postgresql://{{ db_host }}/sonar
              volumes:
                - sonar_data:/opt/sonarqube/data
                - sonar_extensions:/opt/sonarqube/extensions
                - sonar_logs:/opt/sonarqube/logs
          volumes:
            sonar_data:
            sonar_extensions:
            sonar_logs:

    - name: 7. Run Containerized Stack
      command:
        cmd: docker compose up -d
        chdir: /opt/sonar-ha-stack